### ISSUE TITLE
Handle reservations

### ISSUE THREAD

**Issue by katima-g33k** [jessylachapelle/blu-desktop#48]
## Tasks
- [x] Only Parents can reserve
- [x] Handle reservations of copies
- [x] Handle reservation of items
- [x] Cannot reserve item if copy in stock
- [x] Reservation popup when copy is added
- [x] Cancel reservation (item & copy)
- [x] Remove reservation when copy sold
- [x] Display reservations item view
- [x] Display reservations member view
